CREATE DATABASE ConnectPlus;

USE	ConnectPlus;

CREATE TABLE TipoContato(
    IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Titulo VARCHAR(100) NOT NULL
);
GO

CREATE TABLE Contato(
    IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
    Nome VARCHAR(100) NOT NULL,
    Imagem VARCHAR(100),
    FormaContato VARCHAR(100) NOT NULL,
    IdTipoContato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);
GO